name: Create Repository
on: 
  workflow_dispatch:
    inputs:
      repo-name: 
        description: "Name of the repository to be created"
        required: true
      template:
        description: "Name of template to use"
        default: ''

jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Create Repository
    steps:
      - name: Creating GitHub Repository
        run: gh repo create ${{ inputs.repo-name }}