name: Run terraform from PR

on:
  pull_request:
    paths:
      - '*.tf'

jobs:
  call-terraform-workflow:
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    uses: liamfit/workflow-library/.github/workflows/terraform-plan-and-apply.yml@9aa8e4864d2e12d0ebb568505294e0027de736a0
    with:
      environment: mgmt
      terraform-version: 1.3.6
    secrets: inherit