name: Run terraform from PR

on:
  pull_request:
    paths:
      - '*.tf'

jobs:
  call-terraform-workflow:
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    uses: liamfit/workflow-library/.github/workflows/terraform-plan-and-apply.yml@72590653192b5217dddc7aaf1a96838dacf1f1d4
    with:
      environment: mgmt
      terraform-version: 1.3.6
    secrets: inherit